custom: ["https://github.com/JakubRobaszek/ZbiorZadanPUT"]

# Informacja: Nie przyjmuję darowizn. Możesz przyczynić się do rozwoju projektu, 
# zgłaszając błędy, proponując nowe funkcje lub przesyłając swoje rozwiązania w pull requestach.
